global:
  scrape_interval:     30s # El intervalo en el que se traerá las métricas
  evaluation_interval: 30s # Evaluará las reglas cada 30 segundos, por defecto es cada minuto

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['node_exporter:9100']